### ISSUE TITLE
Network regarding issue

### ISSUE THREAD

**Issue by therichiekumar** [xvrh/lottie-flutter#54]
I Have my flutter app with firestore. I use  Lottie.network(), it works fine with the example link provided by you, But my link does not work fine. I can't figure out what's going wrong.
your example link: https://raw.githubusercontent.com/xvrh/lottie-flutter/master/example/assets/Mobilo/A.json
My link: https://raw.githubusercontent.com/therichiekumar/thejson/master/20880-stay-home-stay-safe.json

Kind Regards.

**Comment by xvrh** [comment]
Hi, 
Thanks for the report.
I tried your link and I'm able to see your animation. 
Could it be that this is because the animation is white that you don't see it?

![Screenshot 2020-05-03 at 14 58 37](https://user-images.githubusercontent.com/5110923/80914844-9c737800-8d4e-11ea-9f03-b5c6be243ecd.png)

**Comment by therichiekumar** [comment]
Yes...
